#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=05

start_service() {
    procd_open_instance
    procd_set_param command /App/webhook/webhook -hooks /App/webhook/webhook.conf -port 8888 -verbose
    procd_set_param respawn 3600 5 5
    procd_close_instance
}
